Implement the getBalance method for the KuCoin Service
skubarenko/trader-services pull request #28
Opened 2018-05-15 14:23 UTC by skubarenko

2018-05-15 14:37 UTC, skubarenko commented on src/services/kucoin/constants.ts
> +export const KUCOIN_GET_BALANCE_OF_COIN_URI = (coin: string) => `v1/account/${coin}/balance`;
@maxima-net , what do you think of this format? 
Some URIs depend on parameters as such as the 'coin'. In this case, we need to use format strings as such as:
* `'v1/account/{0}/balance'` - the .NET style
* `'v1/account/%s/balance'` - the `printf` style
* `'v1/account/{coin}/balance'` - a custom style

I think the best solution will be using a function because a user of the URI doesn't need to know that it is a format string.

2018-05-22 15:54 UTC, maxima-net commented on src/services/kucoin/constants.ts
> +export const KUCOIN_GET_BALANCE_OF_COIN_URI = (coin: string) => `v1/account/${coin}/balance`;
I like this style
getBalanceUri = (coin: string) => `v1/account/${coin}/balance`

2018-06-02 09:39 UTC, maxima-net requested changes

2018-06-02 09:39 UTC, maxima-net commented on src/services/kucoin/kucoin-nonce-generator.ts
> +export const kuCoinNonceGenerator = () => Date.now();
Let's rename this function. It looks like a class. May be... getKuCoinNonce() or generateKuCoinNonce()

2018-06-02 10:54 UTC, skubarenko commented on src/services/kucoin/kucoin-nonce-generator.ts
> +export const kuCoinNonceGenerator = () => Date.now();
Ok, let’s rename it. I’ve just thought to make this function as a generator function in the future

2018-06-02 17:31 UTC, skubarenko commented on src/services/kucoin/kucoin-nonce-generator.ts
> +export const kuCoinNonceGenerator = () => Date.now();
Though, it's still better to use an one of `generator`, `factory`, `factoryMethod`. Because this function will be used as the field/property of the service class. And when a user sees it:
![image](https://user-images.githubusercontent.com/13188494/40879032-aaac44bc-66a2-11e8-9dd3-dc36ee922456.png)
The user will most likely be confused by the `getNonce` member.  He or she will think that it's normal public method and they might call it to get nonce value. Though it will be a property to set a fabric method/generator for the service.

2018-06-02 18:42 UTC, maxima-net commented on src/services/kucoin/kucoin-nonce-generator.ts
> +export const kuCoinNonceGenerator = () => Date.now();
So... What if we create a `nonceGenerator` property returned a real generator?
usage example: `kuCoinSerivce.nonceGenerator.next();`

2018-06-04 09:18 UTC, skubarenko commented on src/services/kucoin/kucoin-nonce-generator.ts
> +export const kuCoinNonceGenerator = () => Date.now();
I think the `Factory` postfix is the best variant at the moment

2018-06-05 14:22 UTC, maxima-net approved these changes

2018-06-05 14:22 UTC, merged