Split the ExchangeService interface into RestExchangeService and Auth…
skubarenko/trader-services pull request #60
Opened 2018-05-24 09:07 UTC by skubarenko

…enticatedRestExchangeService. Rename the getRecentDealOrders method to getTrades. Create the Identified type

2018-05-24 20:17 UTC, maxima-net requested changes

2018-05-24 20:17 UTC, maxima-net commented on src/utils/identifier.ts
> +};
Is this a guard? Shell we use the "Guard" as a name postifx here?

2018-05-24 20:17 UTC, maxima-net commented on src/utils/identifier.ts
> +
Are you sure that id must have a string type, not a number?

2018-05-25 08:45 UTC, skubarenko commented on src/utils/identifier.ts
> +};
Yes, it's a guard, but I think that the "Guard" postfix is redundant. See the `nodejs` guards:
```ts
export function isNullOrUndefined(object: any): object is null | undefined;
export function isNumber(object: any): object is number;
export function isObject(object: any): boolean;
```
and examples in (http://www.typescriptlang.org/docs/handbook/advanced-types.html)[the official documentation] of typescript:
```ts
function isFish(pet: Fish | Bird): pet is Fish {
    return (<Fish>pet).swim !== undefined;
}
```

2018-05-25 08:48 UTC, skubarenko commented on src/utils/identifier.ts
> +
No, I'm not 😄  Need to check API methods of popular services to select the type correctly

2018-05-25 09:22 UTC, maxima-net commented on src/utils/identifier.ts
> +};
Ok. I agree.

2018-05-30 12:16 UTC, maxima-net commented on src/utils/identifier.ts
> +
Ok, Let's make it string. It's safer then number typer.

2018-05-30 12:16 UTC, maxima-net approved these changes

2018-05-30 12:17 UTC, merged