Add Yobit's getBalance method. Little refactoring
skubarenko/trader-services pull request #93
Opened 2018-06-11 09:13 UTC by maxima-net

2018-06-11 13:43 UTC, skubarenko requested changes

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/constants.ts
> +    rootPublicApiUrl: `${rootServerUrl}/api/3`,
It's not a root url. Plus, the `constants` doesn't contain `rootServerUrl`. If you want to give information about parts of private/public api uris, I propose to use the following code:
```ts
const rootServerUrl = 'https://yobit.net';
const publicApiUri = `${rootServerUrl}/api/3`;
const privateApiUri = `${rootServerUrl}/tapi`;

const constants = {
    rootServerUrl,
    publicApiUri,
    privateApiUri,
    getOrderBookUri: (pair: CurrencyPair) => `${publicApiUri}/depth/${YobitUtils.getPairSymbol(pair)}`,
    getTradesUri: (pair: CurrencyPair) => `${privateApiUri}/trades/${YobitUtils.getPairSymbol(pair)}`,
    balanceMethod: 'getInfo'
};
```

Then you'll have one variable of `rootServerUrl` which a user can replace to own url in the service, for example own proxy url.

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-service.ts
> +    constructor(requestTryCount: number = 3) {
Here will be passing of the `rootServerUrl` that is can be replaced.

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPublicApiUrl,
`YobitConstants.rootPublicApiUrl` will be replaced by `this.serverUri`

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPublicApiUrl,
`YobitConstants.rootPublicApiUrl` will be replaced by `this.serverUri`

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPrivateApiUrl,
`YobitConstants.rootPrivateApiUrl` -> `this.serverUri`

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +interface YobitSuccessResultContainer {
What's a container? Is it a response result?

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +        return data && data.success && data.success === 1 && data.return;
Does the `return` field always contain a value? Can't it contain `undefined`? For example, some operations of the KuCoin can contain undefined and null values and so I ask about it

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
Can we change the type of this field to `{ [currencyName: string]: number; }`?

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-nonce-factory.ts
> +export const YobitNonceFactory = () => Date.now() / 10000;
Let's rename it with a lower case first char. It's not a class, type, namespace, it's a function.

2018-06-11 13:43 UTC, skubarenko commented on src/services/yobit/yobit-signature-maker.ts
> +        for (const key in params)
I'd really to use `Object.getOwnPropertyNames`:
```ts
Object.getOwnPropertyNames(params)
    .forEach(key => paramsForSignArray.push(`${key}=${params[key]}`));
```

Though this code will be replaced by the use of the `qs` package in the future

2018-06-11 13:43 UTC, skubarenko commented on tests/services/yobit/data/balance.ts
> +    defaultLtcBalance: {
I suggest you start to add the error case for server error testing. Look at some data of the KuCoin service

https://github.com/CryptoKraken/crypto-kraken-services/blob/9e8442707355f279d71ca683759a8ea8d139f585/tests/services/kucoin/data/active-orders.ts#L65-L71

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/constants.ts
> +    rootPublicApiUrl: `${rootServerUrl}/api/3`,
I agree, but I wasn't gonna fix #79 in this PR. I'll consider your tips for fixing. Ok? I'll fix it with another PR.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-service.ts
> +    constructor(requestTryCount: number = 3) {
Ok, I agree. But read a previous answer, please.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPublicApiUrl,
Ok, I agree. But read a previous answer, please.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPublicApiUrl,
Ok, I agree. But read a previous answer, please.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-service.ts
> +                baseUrl: YobitConstants.rootPrivateApiUrl,
Ok, I agree. But read a previous answer, please.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +interface YobitSuccessResultContainer {
Yes. It's a common response result for all auth operations.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +        return data && data.success && data.success === 1 && data.return;
I can't see that result can contain undefined. If I'll face with this, I'll change it.

2018-06-12 15:41 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
Yes, I'll change it.

2018-06-12 15:42 UTC, maxima-net commented on src/services/yobit/yobit-nonce-factory.ts
> +export const YobitNonceFactory = () => Date.now() / 10000;
Ok, My mistake.

2018-06-12 15:42 UTC, maxima-net commented on src/services/yobit/yobit-signature-maker.ts
> +        for (const key in params)
Yes, I've wanted to replace it with qs. It'is still WIP. So I didn't expect review at this moment.

2018-06-12 15:42 UTC, maxima-net commented on tests/services/yobit/data/balance.ts
> +    defaultLtcBalance: {
Every Yobit parser's method has this test. I moved common error response to data/common.ts
```ts
export const yobitGeneralError = {
    success: 0,
    error: 'Yobit error text'
};

```

2018-06-12 16:04 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
Thought, I wanted to check existence for `funds` and `funds_incl_orders` properties only. So 
I don't want to check all inner properties if I need only one of each.

For example I need to get `ltc` balance. That is a response:
```
return: {
   funds: {
       ltc: 22.5,
       nvc: 423.998,
       ppc: 10,
   },
   funds_incl_orders: {
       ltc: 32,
       nvc: 523.998,
       ppc: 20,
   }
}
```
I really need to check existence of `return` then `return.found` and `return.funds_incl_orders` and then `return.found.ltc` and `return.funds_incl_orders.ltc`.

So it can be expensive and redundant to check all properties types for `funds` and `funds_incl_orders` objects.

Do you agree?

2018-06-12 20:12 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
I've not understood you. How does field checking relate to their type? I suggested you to replace the `any` type to `{ [currencyName: string]: number; }`:
```ts
interface YobitBalanceContainer {
    funds: { [currencyName: string]: number; };
    funds_incl_orders: { [currencyName: string]: number; };
}
```

2018-06-12 20:13 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +        return data && data.success && data.success === 1 && data.return;
Ok

2018-06-12 20:18 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +interface YobitSuccessResultContainer {
Well, then can we rename it? We should make it is consistent with the KuCoin parser. Or vice versa.

2018-06-12 20:19 UTC, skubarenko commented on tests/services/yobit/data/balance.ts
> +    defaultLtcBalance: {
Good

2018-06-12 20:31 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
I'll try to explain:

I need only one coin balance. But `funds` fields contain all coins.
I don't check other coin fields in the object. So I cant promise that funds contain all properties with type number. Only `ltc` field in this context

There is a result
```
return: {
   funds: {
       ltc: 22.5,               // I check and use only this field
       nvc: 423.998,       // I don't check and use these field
       ppc: 10,               // I don't check and use these field
   },
   funds_incl_orders: {
       ltc: 32,                 // I check and use only this field
       nvc: 523.998,       // I don't check and use these field
       ppc: 20,               // I don't check and use these field
   }
}
```

2018-06-12 20:49 UTC, skubarenko commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
Ok, I understood it. I've not understood what are troubles with the concrete type? If there will this interface:
```ts
interface YobitBalanceContainer {
    funds: { [currencyName: string]: number; };
    funds_incl_orders: { [currencyName: string]: number; };
}
```

Then you can also check concrete coin field
```ts
const allAmount = dataObject.return.funds_incl_orders[currency];
const freeAmount = dataObject.return.funds[currency];
```

Only, types of the `allAmount` and `freeAmount` already will be known: they are `numbers`.

2018-06-13 15:57 UTC, maxima-net commented on src/services/yobit/yobit-response-parser.ts
> +    funds: any;
`currency` is a dynamic field. So I can't use it in guards.
I check that in two steps. First: checking existence of `funds` and `funds_incl_orders` fields.
Second: checking existence of return.found[currency] and return.funds_incl_orders[currency] fields and checking their type

2018-06-13 17:03 UTC, skubarenko approved these changes

2018-06-13 17:03 UTC, merged